#!/usr/bin/env python
# Other special characters'
special = {
  'smile' : ('Smilie with circle around it', [
     '  GGGG  ',
     ' G    G ',
     'G G  G G',
     'G      G',
     'G G  G G',
     'G  GG  G',
     ' G    G ',
     '  GGGG  ', 
  ]),
  'smilie' : ('Green smilie with no circle', [
     ' GG  GG ',
     ' GG  GG ',
     '        ',
     '   GG   ',
     'G  GG  G',
     'GG    GG',
     'GGGGGGGG',
     '  GGGG  ', 
  ]),
  'frownie' : ('Red frown with no cirle', [
     ' RR  RR ',
     ' RR  RR ',
     '        ',
     '   RR   ',
     '        ',
     ' RRRRRR ',
     'RRRRRRRR',
     'R      R', 
  ]),
  'sad' : ('Sad red smilie with circle around it', [
     '  RRRR  ',
     ' R    R ',
     'R R  R R',
     'R      R',
     'R  RR  R',
     'R R  R R',
     ' R    R ',
     '  RRRR  ', 
  ]),
  'green' : ('Solid green', [
     'GGGGGGGG',
     'GGGGGGGG',
     'GGGGGGGG',
     'GGGGGGGG',
     'GGGGGGGG',
     'GGGGGGGG',
     'GGGGGGGG',
     'GGGGGGGG', 
  ]),
  'red' : ('Solid red', [
     'RRRRRRRR',
     'RRRRRRRR',
     'RRRRRRRR',
     'RRRRRRRR',
     'RRRRRRRR',
     'RRRRRRRR',
     'RRRRRRRR',
     'RRRRRRRR', 
  ]),
  'orange' : ('Solid orange', [
     'OOOOOOOO',
     'OOOOOOOO',
     'OOOOOOOO',
     'OOOOOOOO',
     'OOOOOOOO',
     'OOOOOOOO',
     'OOOOOOOO',
     'OOOOOOOO', 
  ]),
}
